version: "3.8"

services:
  nginx:
    image: nginx:1.25
    ports:
      - "1243:80"
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go_app
    networks:
      - vita

  go_app:
    image: golang:1.22-alpine
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/app
    environment:
      - TZ=Europe/Samara
      - PORT=8080
    depends_on:
      - postgres_db
    networks:
      - vita

  postgres_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vita
      - POSTGRES_USER=login
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - vita

networks:
  vita:
    driver: bridge

volumes:
  pg_data:
